package com.module.autographs.lcvregistration.microservice.util;

public class Constants {

    // HTTP STATUS CODES
    public static final String HTTP_RESPONSE_CODE_OK = "200";
    public static final String HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR = "500";

    // ALL API PATHS

    // 1 - NEW LCV REGISTRATIONS
    public static final String NEW_LCV_REGISTRATION_GET_API_PATH = "/getAllNewLCVRegistrationsData";
    public static final String NEW_LCV_REGISTRATION_POST_API_PATH = "/addNewLCVRegistrationsData";
    public static final String NEW_LCV_REGISTRATION_DELETE_ALL_API_PATH = "/deleteAllNewLCVRegistrationsData";

    // 2 - NEW LCV REGISTRATIONS BY FUEL TYPE
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_GET_API_PATH = "/getAllNewLCVRegistrationsByFuelTypeData";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_POST_API_PATH = "/addNewLCVRegistrationsByFuelTypeData";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_API_PATH = "/deleteAllNewLCVRegistrationsByFuelTypeData";

    // 3 - NEW LCV REGISTRATIONS BY SALES TYPE
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_GET_API_PATH = "/getAllNewLCVRegistrationsBySalesTypeData";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_POST_API_PATH = "/addNewLCVRegistrationsBySalesTypeData";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_API_PATH = "/deleteAllNewLCVRegistrationsBySalesTypeData";


    // ALL SWAGGER CONSTANTS BELOW ---------------------------------------------------------------------------------------------------------


    // 1 - NEW LCV REGISTRATIONS
    // GET API
    public static final String NEW_LCV_REGISTRATION_GET_SUMMARY = "GET - NEW LCV REGISTRATION DATA";
    public static final String NEW_LCV_REGISTRATION_SUCCESS = "NEW LCV REGISTRATION DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_NO_DATA_FOUND = "NO DATA FOUND FOR NEW LCV REGISTRATION.";
    // POST API
    public static final String NEW_LCV_REGISTRATION_POST_SUMMARY = "POST - ADD NEW LCV REGISTRATIONS";
    public static final String NEW_LCV_REGISTRATION_ADD_SUCCESS = "NEW LCV REGISTRATIONS DATA ADDED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW LCV REGISTRATION DATA.";
    // DELETE API
    public static final String NEW_LCV_REGISTRATION_DELETE_ALL_SUMMARY = "DELETE ALL - NEW LCV REGISTRATION DATA";
    public static final String NEW_LCV_REGISTRATION_DELETE_ALL_SUCCESS = "NEW LCV REGISTRATION DATA DELETED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW LCV REGISTRATION DATA.";

    // 2 - NEW LCV REGISTRATIONS BY FUEL TYPE
    // GET API
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_GET_SUMMARY = "GET - NEW LCV REGISTRATION BY FUEL TYPE DATA";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_SUCCESS = "NEW LCV REGISTRATION BY FUEL TYPE DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_NO_DATA_FOUND = "NO DATA FOUND FOR NEW LCV REGISTRATION BY FUEL TYPE.";
    // POST API
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_POST_SUMMARY = "POST - ADD NEW LCV REGISTRATION BY FUEL TYPE";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_ADD_SUCCESS = "NEW LCV REGISTRATIONS DATA BY FUEL TYPE ADDED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW LCV REGISTRATION BY FUEL TYPE DATA.";
    // DELETE API
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_SUMMARY = "DELETE ALL - NEW LCV REGISTRATION BY FUEL TYPE  DATA";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_SUCCESS = "NEW LCV REGISTRATION BY FUEL TYPE DATA DELETED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW LCV REGISTRATION BY FUEL TYPE DATA.";


    // 3 - NEW LCV REGISTRATIONS BY SALES TYPE
    // GET API
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_GET_SUMMARY = "GET - NEW LCV REGISTRATION BY SALES TYPE DATA";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_SUCCESS = "NEW LCV REGISTRATION BY SALES TYPE DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_NO_DATA_FOUND = "NO DATA FOUND FOR NEW LCV REGISTRATION BY SALES TYPE.";
    // POST API
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_POST_SUMMARY = "POST - ADD NEW LCV REGISTRATION BY SALES TYPE";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_ADD_SUCCESS = "NEW LCV REGISTRATIONS DATA BY SALES TYPE ADDED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW LCV REGISTRATION BY SALES TYPE DATA.";
    // DELETE API
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_SUMMARY = "DELETE ALL - NEW LCV REGISTRATION BY SALES TYPE  DATA";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_SUCCESS = "NEW LCV REGISTRATION BY SALES TYPE DATA DELETED SUCCESSFULLY.";
    public static final String NEW_LCV_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW LCV REGISTRATION BY SALES TYPE DATA.";

}
